import React, { useEffect } from "react"; import { Icon } from "../components/Icon"; import { Link } from "../lib/router";
const programs = [
  { title:"Kids Quran Classes", route:"/kids-quran-classes", icon:"BookOpen", learner:"Children ages 4–15", outcome:"Build confident Quran reading through an age-aware private pathway.", book:true },
  { title:"Adult Quran Classes", route:"/adult-quran-classes", icon:"User", learner:"Adult beginners and returning learners", outcome:"Learn from the right starting point at a respectful, private pace.", book:true },
  { title:"Tajweed Course", route:"/tajweed-course", icon:"AudioLines", learner:"Teens and adults improving recitation", outcome:"Apply Makharij, Sifaat and Tajweed rules in guided recitation.", book:true },
  { title:"Hifz Program", route:"/hifz-program", icon:"Layers", learner:"Learners beginning or strengthening Hifz", outcome:"Balance new memorization with recent and long-term revision.", book:true },
  { title:"Arabic Language", route:"/arabic-language", icon:"Languages", learner:"Learners seeking an Arabic pathway", outcome:"Explore reading, vocabulary, structure and comprehension.", status:"Phase 1: consultation-based" },
  { title:"Islamic Studies", route:"/islamic-studies", icon:"Library", learner:"Eligible Quran-program learners", outcome:"Add suitable Islamic foundations alongside Quran learning.", status:"Phase 1: add-on, not standalone" }
];
export const Programs:React.FC=()=>{useEffect(()=>{document.title="Online Quran Programs | Tajweed Scholars"},[]);return <div id="programs-page"><section className="border-b bg-emerald-50 py-12 sm:py-16"><div className="mx-auto max-w-5xl px-4 text-center sm:px-6"><p className="text-xs font-bold text-emerald-800">Six clear learning pathways</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">Find the right Quran learning program.</h1><p className="mx-auto mt-4 max-w-2xl leading-7 text-stone-600">Private one-to-one classes for children and adults, from first letters through Tajweed and Hifz.</p></div></section><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{programs.map(p=><article key={p.route} className="flex flex-col rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-emerald-50 text-emerald-800"><Icon name={p.icon}/></span><h2 className="mt-5 text-xl font-bold">{p.title}</h2><p className="mt-2 text-sm font-semibold text-emerald-800">Suitable for: {p.learner}</p><p className="mt-3 flex-1 text-sm leading-6 text-stone-600">{p.outcome}</p>{p.status&&<p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs font-bold text-amber-800">{p.status}</p>}<div className="mt-5 grid gap-2"><Link to={p.route} className="inline-flex min-h-11 items-center justify-center rounded-lg border border-emerald-700 px-4 text-sm font-bold text-emerald-800">View Program</Link>{p.book&&<Link to="/free-trial" className="inline-flex min-h-11 items-center justify-center rounded-lg bg-emerald-800 px-4 text-sm font-bold text-white">Book 3 Free Trial Classes</Link>}</div></article>)}</div></main></div>}
