import type { TrialFaq } from "../components/TrialFaqAccordion";
export const PROGRAM_VISUALS: Record<string,{title:string;items:string[]}> = {
  "kids-classes": { title:"Age-based learning path", items:["Ages 4–6","Ages 7–9","Ages 10–12","Ages 13–15"] }, "adult-classes": { title:"Choose your starting point", items:["Starting from zero","Reading but struggling","Improving Tajweed"] }, "tajweed-course": { title:"Practical Tajweed pathway", items:["Makharij","Sifaat","Noon & Meem","Madd","Applied recitation"] }, "hifz-program": { title:"Balanced memorization cycle", items:["Sabaq · new lesson","Sabqi · recent revision","Manzil · long-term revision"] }, "arabic-language": { title:"Consultation-based pathway", items:["Reading","Vocabulary","Sentence structure","Comprehension"] }, "islamic-studies": { title:"Add-on topic pathway", items:["Aqeedah","Salah & Fiqh","Seerah","Islamic manners","Daily duas","Prophet stories"] }
};
export const PROGRAM_FAQS: Record<string,TrialFaq[]> = {
 "kids-classes":[["Is the program suitable for complete beginners?","Yes. Trial 1 establishes the appropriate starting point."],["How is my child’s starting level decided?","The teacher checks current skills during the three trials."],["How do you keep younger children engaged?","Teachers use short activities, repetition, and patient encouragement."],["Will parents receive progress updates?","Families receive regular progress updates, attendance notes, homework updates, teacher feedback, and clear next goals."],["Can siblings book separate trials?","Yes. Each learner needs a separate request."]],
 "adult-classes":[["Can I start if I cannot read Arabic?","Yes. Complete beginners may begin with letters and Qaida."],["Are classes private?","Yes. Classes are live, private, and one-to-one through Zoom."],["Can I focus only on Tajweed correction?","Yes, after suitable placement."],["Can I request a male or female teacher?","Preferences are considered subject to suitable availability."],["How is my starting level assessed?","Trial 1 includes placement and a real mini-lesson."]],
 "tajweed-course":[["Do I need to read Quran before joining?","Trial 1 confirms whether foundational reading support is needed first."],["Will the teacher correct Makharij?","Yes, through listening and guided practice."],["Are Tajweed rules taught practically?","Yes. Rules are applied directly during recitation."],["Is the course suitable for adults and teens?","Yes. Placement and pace are adapted to the learner."],["How is progress reviewed?","Through regular feedback, homework updates, and clear next goals."]],
 "hifz-program":[["What are Sabaq, Sabqi and Manzil?","Sabaq is new memorization, Sabqi recent revision, and Manzil long-term revision."],["Can I join if I already attend a Hifz school?","Yes. Placement identifies suitable private support."],["How is the daily memorization target decided?","The teacher considers retention, fluency, revision load, and study time."],["Is Tajweed corrected during Hifz?","Yes. Accurate recitation remains part of memorization."],["How are revision and progress tracked?","Through revision checks, homework updates, feedback, and next goals."]],
 "arabic-language":[["Is Arabic available as a fixed Phase 1 program?","No. Phase 1 availability is consultation-based."],["Do you teach Quranic Arabic or Modern Standard Arabic?","Either may be considered during consultation."],["How is placement confirmed?","Admissions confirms the suitable pathway after consultation."],["Is the program suitable for beginners?","Beginners may inquire; placement remains consultation-based."]],
 "islamic-studies":[["Is Islamic Studies available as a standalone program?","No. It is initially an add-on alongside eligible Quran programs."],["Which topics may be included?","Aqeedah, Salah and Fiqh, Seerah, manners, daily duas, and Prophet stories may be included."],["Is it available for children and adults?","It may support eligible child or adult Quran learners."],["How is it added to a Quran program?","Admissions confirms eligibility and scheduling."]]
};
export const PRICING_FAQS: TrialFaq[]=[["What is included in every plan?","Live private Zoom classes, a dedicated teacher, 30-minute lessons, structured learning, and regular progress updates."],["Are fees charged monthly?","Yes. Displayed fees are monthly."],["Can I change the number of classes per week?","Contact admissions to discuss another frequency."],["Are weekend plans available?","Yes. One-day and two-day weekend options are listed."],["Which currencies can I view?","USD, GBP, CAD, and AUD."],["When do I receive payment instructions?","After the trials, official instructions may use Remitly, TapTap Send, or direct/manual bank transfer where available."],["What happens after the free trials?","Trial 3 concludes with a no-pressure recommendation."]];
export const CONTACT_FAQS: TrialFaq[]=[["Should I use this page or the Free Trial form?","Use the Free Trial form for new learner placement; use this page for other questions."],["What is the fastest way to reach admissions?","WhatsApp is the primary direct admissions contact shown here."],["Can existing families request a schedule change?","Yes. Contact admissions to discuss available options."],["How are payment instructions shared securely?","Only through official Tajweed Scholars channels; public bank details are not posted."]];
