export interface PolicySection {
  heading: string;
  paragraphs?: string[];
  closingParagraphs?: string[];
  bullets?: string[];
  steps?: string[];
  table?: { headers: string[]; rows: string[][] };
}

export interface PolicyContent {
  title: string;
  summary: string;
  sections: PolicySection[];
}

export const POLICY_NOTICE = "These are working policies for Phase 1 of Tajweed Scholars and may be updated as the academy grows — the most current version always applies.";
export const POLICY_LAST_UPDATED = "Phase 1 publication";

export const POLICIES: Record<string, PolicyContent> = {
  "/terms-and-conditions": {
    title: "Terms & Conditions",
    summary: "These Terms & Conditions set out the agreement between Tajweed Scholars and any family or adult learner who books a trial class, enrols in a paid plan, or otherwise uses our services. They explain, in plain language, what you can expect from us and what we ask of you.",
    sections: [
      { heading: "What We Provide", paragraphs: ["Tajweed Scholars provides private, live, one-to-one online classes in Quran reading, Tajweed, Hifz, Arabic, and Islamic Studies, delivered over Zoom by a teacher matched to the student's age and level. Every regular class is 30 minutes long. We currently serve families and adult learners based in the United States, United Kingdom, Canada, and Australia."] },
      { heading: "Enrolling a Child Under 18", paragraphs: ["If a student is under 18, a parent or legal guardian must complete enrolment and acts as the point of contact for all scheduling, communication, and payment matters. By enrolling, the parent or guardian confirms they have the authority to do so, and to give any consent required for the class (for example, consent to recording, where relevant). We ask parents to help ensure a quiet, private space for the child's class and to support consistent attendance."] },
      { heading: "Respectful Conduct", paragraphs: ["We ask every student, parent, and teacher to treat one another with courtesy and respect. We do not tolerate abusive, threatening, or discriminatory behaviour toward any teacher, student, or staff member, whether during a live class or in written communication. A teacher who does not meet our professionalism or safeguarding standards will be reassigned or removed from teaching."] },
      { heading: "No Guaranteed Timeline or Outcome", paragraphs: ["Learning pace varies from student to student, and Tajweed Scholars does not guarantee a fixed timeline for completing any level, memorisation milestone, or certification. Any duration mentioned on our website, in a programme description, or by a teacher is a planning estimate only, and is reviewed and adjusted based on the student's real progress — this applies with particular emphasis to the Hifz Programme, which is paced individually."] },
      { heading: "Your 3 Free Trial Classes", paragraphs: ["Every new family or adult learner receives 3 free trial classes before any payment is requested. No payment details are collected to book a trial."], bullets: ["Trial 1 — Assessment & Connection. This is your placement assessment. Your (or your child's) starting level is confirmed live, during real teaching — there is no separate assessment session beforehand.", "Trial 2 — Real Learning Experience. A full lesson at the confirmed level.", "Trial 3 — Confidence & Enrolment Recommendation. A final lesson, a short progress recap, and a clear recommendation. Pricing and enrolment are discussed separately by our Admissions team afterward — never during a trial class itself."] },
      { heading: "Rescheduling and Attendance", paragraphs: ["Classes can be rescheduled with reasonable notice — see our Reschedule & Make-Up Class Policy for the exact notice windows and process. Because consistency drives real progress, we may reach out if a family experiences repeated late cancellations or no-shows, simply to help find a schedule that works better."] },
      { heading: "Changes to These Terms", paragraphs: ["We may update these Terms from time to time as Tajweed Scholars introduces new features or programmes. Families will be notified of any material change before it takes effect. Nothing in these Terms limits any statutory consumer rights you hold under the law of your own country, which always take precedence."] },
      { heading: "Contact and Escalation", paragraphs: ["Questions about these Terms can be sent through our official Contact page, email, or WhatsApp channel. If a concern is not resolved by our Admissions or Parent Success team, it is escalated to the Tajweed Scholars Operations Lead for a final response. See our Complaints Process page for the full escalation path."] },
    ],
  },
  "/payment-policy": {
    title: "Payment Policy",
    summary: "This policy explains how and when Tajweed Scholars charges for enrolled classes, once you've completed your 3 free trial classes and chosen to enrol. Nothing is billed before then, and we aim to remove any surprises from the billing relationship.",
    sections: [
      { heading: "Your Plan and Pricing", paragraphs: ["Tajweed Scholars offers a range of monthly plans covering 1 to 5 classes a week, as well as weekend-only options. Every plan includes a 30-minute session length, a dedicated one-to-one teacher, and regular progress updates. Your Admissions Advisor will confirm the exact plan and price for your family after Trial 3, in your local currency."] },
      { heading: "When You're Billed", bullets: ["Billing is monthly and recurring, beginning on the date you confirm your plan after Trial 3.", "Plans renew automatically each month and can be cancelled at any time after the initial term.", "Payment for a billing cycle is completed before that cycle's classes begin, so your teacher's schedule and your regular time slot are properly secured.", "If you enrol partway through a month, your first payment is adjusted to cover the period from your start date to the next standard renewal date."] },
      { heading: "How to Pay", paragraphs: ["For Phase 1, Tajweed Scholars accepts payment through approved manual transfer methods, including Remitly, TapTap Send, or direct bank transfer where available. Payments are currently received into the Founder's account on behalf of Tajweed Scholars. Payment instructions are shared only through our official Tajweed Scholars communication channels — never by a teacher, and never through any unofficial route. Please do not send payment to any account or number that has not been confirmed through our official channels.", "Your billing currency is fixed to your confirmed country at enrolment. If you later need to change currency, this requires setting up a new plan rather than converting mid-cycle."] },
      { heading: "If a Payment Is Missed", paragraphs: ["If a payment does not go through by the renewal due date, we will contact you directly first, before taking any further action. If payment remains outstanding for 3 calendar days past the due date, the student's regular class slot may be paused until payment is resolved. A pause is not a cancellation — your level placement and, wherever possible, your assigned teacher are kept in place."] },
      { heading: "Changing Your Plan or Enrolling Multiple Children", paragraphs: ["You can change your class frequency at any time by speaking with your Admissions Advisor; the new plan applies from your next billing cycle. Family and sibling arrangements are available on request — please speak with your Admissions Advisor, as these are confirmed individually with Founder approval."] },
      { heading: "Contact and Escalation", paragraphs: ["Billing questions can be directed to our Admissions or Parent Success team by WhatsApp or through our Contact page. If you believe you have been charged in error, please let us know as soon as possible so it can be corrected — see our Refund Policy for how corrections are handled."] },
    ],
  },
  "/refund-policy": {
    title: "Refund Policy", summary: "This policy explains what happens if a class is missed — by the student, the teacher, or due to a scheduling issue on our end — and how refunds are handled for paid plans.",
    sections: [
      { heading: "Your 3 Trial Classes Are Always Free", paragraphs: ["All three trial classes are completely free, with no payment details collected to book them. Because they are never billed, there is nothing to refund for a trial class."] },
      { heading: "How Paid Plans Work", paragraphs: ["Once you enrol, your monthly plan is billed in advance of that cycle's classes. Because you're paying for an ongoing plan rather than pre-purchased individual sessions, refunds are handled at the plan level rather than as an automatic per-class request."] },
      { heading: "If a Class Is Missed by the Student", paragraphs: ["If a scheduled class is missed without the required notice (at least 24 hours for Kids Quran Classes and any student under 18, or at least 4 hours for Adult Quran Classes), that class is not automatically refunded or credited. If you reschedule within the notice window, the class is moved at no penalty and no loss of credit — see our Reschedule & Make-Up Class Policy for the full process."] },
      { heading: "If a Class Is Missed Because of Us", paragraphs: ["If a scheduled class doesn't happen because of a technical issue on our side, or because your assigned teacher is unavailable and no substitute could be arranged, you are never simply left to lose that class. We will always reschedule it or credit it to your account. You are never charged for a class that Tajweed Scholars or your teacher failed to deliver."] },
      { heading: "Pausing or Cancelling", paragraphs: ["You may pause your subscription for travel, Ramadan restructuring, or personal circumstances without losing your level placement or, wherever possible, your teacher — no charge is billed during an approved pause. If you cancel mid-cycle, you will not be billed for the following cycle. We do not offer partial-month refunds for a cycle already in progress, except where a class was missed because of us (see above)."] },
      { heading: "How a Refund Is Issued", paragraphs: ["Approved refunds are processed within 7–14 business days of approval, through the original payment route where possible, or another agreed transfer method."] },
      { heading: "Contact and Escalation", paragraphs: ["Refund, credit, or missed-class questions can be raised with our Admissions or Parent Success team through WhatsApp or our Contact page, as soon as possible after the affected class. Unresolved concerns are escalated to the Tajweed Scholars Operations Lead. Nothing in this policy limits your statutory consumer refund rights under the law of your own country."] },
    ],
  },
  "/reschedule-policy": {
    title: "Reschedule & Make-Up Class Policy", summary: "Our classes are live, one-to-one, and built around a consistent weekly rhythm with a single dedicated teacher. Life happens — this policy explains exactly what happens when a class needs to move, so nothing is ever simply lost.",
    sections: [
      { heading: "What This Covers", paragraphs: ["This policy applies to every regularly scheduled, paid 30-minute class across all Tajweed Scholars programmes. It does not cover the three free trial classes, which are scheduled directly with our Admissions team as part of your trial journey."] },
      { heading: "Notice Periods", table: { headers: ["Student", "Minimum Notice to Reschedule"], rows: [["Any student under 18 (Kids Quran Classes, and any minor in another programme)", "At least 24 hours before the scheduled class"], ["Adult learners (18+)", "At least 4 hours before the scheduled class"]] } },
      { heading: "How to Reschedule", paragraphs: ["Message our official Tajweed Scholars WhatsApp number or admissions contact — never your teacher's personal number — with the student's name and the affected class date and time."], bullets: ["Within the notice window: we will reschedule your class, subject to teacher and slot availability. We normally aim to arrange make-up classes within the same week or within 7 days, though this cannot be guaranteed in every case.", "Outside the notice window, or a no-show: the class is recorded as completed under your plan, unless approved as a special case (see Exceptions below).", "Make-up credit is automatic whenever a reschedule falls within the policy window, or whenever a change is caused by Tajweed Scholars rather than by your family."], closingParagraphs: ["If a family experiences frequent late cancellations or no-shows, we won't apply an automatic penalty — instead, our Parent Success team will reach out to understand what's going on and help find a schedule that genuinely fits."] },
      { heading: "Exceptions", bullets: ["Documented emergencies (for example, a medical emergency or bereavement) are considered compassionately, even where notice fell short of the standard window.", "A class affected by a technical issue on our platform, or by teacher unavailability, is never counted against your family and is always rescheduled or credited.", "Tajweed Scholars observes 4 days off for Eid-ul-Fitr and 4 days off for Eid-ul-Adha, with families informed in advance. Ramadan schedules may be adjusted, and any classes affected by an announced holiday are adjusted, rescheduled, or credited accordingly."] },
      { heading: "Contact and Escalation", paragraphs: ["Reschedule requests go through our official WhatsApp number or admissions email. If a request isn't resolved in a reasonable time, or you disagree with how a cancellation was recorded, the matter is escalated to our Parent Success / Admissions lead, and from there to the Operations Lead if needed."] },
    ],
  },
  "/child-safeguarding": {
    title: "Child Safeguarding Policy", summary: "A significant part of our student community is children learning one-to-one over live video. Safeguarding is treated as a first-class, non-negotiable standard at Tajweed Scholars — not a background formality. This policy sets out exactly how we protect every student under 18 in our care.",
    sections: [
      { heading: "Who This Applies To", paragraphs: ["This policy applies to every student under the age of 18 across all Tajweed Scholars programmes, and to every teacher, academic supervisor, and staff member who interacts with a minor student or their family — in a live class, on WhatsApp, or by email."] },
      { heading: "Our Commitments", paragraphs: ["No private contact. Teachers must never contact a minor student, and must never be contacted by one, through a personal phone number, personal social media, or any channel outside official Tajweed Scholars platforms (our official WhatsApp channel, email, or the live Zoom classroom) — even if suggested for convenience.", "A parent or guardian is always the point of contact. For every student under 18, a parent or guardian is the account holder for scheduling, communication, and billing, regardless of the student's independence in class. For younger children, a parent or caregiver being visible during class is expected and welcomed.", "Every teacher is vetted before teaching a child. Our vetting process includes identity verification, Sanad/Ijazah verification, references, a demo class, a signed safeguarding agreement, and a police character certificate where practical.", "No financial or personal requests. A teacher must never request money, gifts, personal information, or a private meeting with a minor student, under any circumstance.", "Recording as one layer of protection. Classes involving minors may be recorded for safeguarding and quality purposes, where consent and policy requirements are met — see our Class Recording & Consent Policy.", "Concerns are reported the same day. Any staff member who becomes aware of a concern about a child's wellbeing — not only academic progress — reports it the same day it is noticed."] },
      { heading: "How We Handle Concerns", paragraphs: ["Any safeguarding concern is raised immediately with our Safeguarding Contact. For Phase 1, this is the Tajweed Scholars Founder / Operations Lead. If they are unavailable, concerns are escalated immediately to the next available senior team member — safeguarding escalation is never delayed for administrative reasons."] },
      { heading: "Contact and Escalation", paragraphs: ["Parents can raise a safeguarding concern at any time through our official WhatsApp number or email. Every concern is treated with urgency and confidentiality."] },
    ],
  },
  "/recording-policy": {
    title: "Class Recording & Consent Policy", summary: "This policy explains, in plain terms, when and why a Tajweed Scholars class may be recorded, how any recording is used and protected, and what consent is required first — so you always know what to expect.",
    sections: [
      { heading: "What This Covers", paragraphs: ["This applies to any live class or trial class delivered over Zoom, across all programmes, for both child and adult students. It does not cover written communication such as WhatsApp or email."] },
      { heading: "When and Why We Record", paragraphs: ["Classes may be recorded for quality assurance, safeguarding, teacher training, or to review a specific concern or dispute — where consent and policy requirements are met. Recording is not framed as an always-on feature of every class."] },
      { heading: "Consent", paragraphs: ["For a student under 18, consent for recording is obtained from the parent or guardian at enrolment or trial booking, and reconfirmed verbally at the start of any class where recording is enabled. For adult learners, consent is obtained directly."] },
      { heading: "How Recordings Are Used", paragraphs: ["A recording is used only for the purpose it was made — quality coaching, safeguarding review, teacher training, or resolving a specific concern. It is never used for marketing, social media, or any public purpose without separate, explicit written permission from you."] },
      { heading: "Who Can Access a Recording", paragraphs: ["Access is limited to authorised Tajweed Scholars staff with a genuine quality, safeguarding, training, or review need. Teachers may access recordings only where approved for coaching, handover, or review."] },
      { heading: "How Long We Keep Recordings", paragraphs: ["Standard quality and safeguarding recordings are retained for 90 days. Recordings connected to an active safeguarding concern, complaint, or dispute may be retained longer, for as long as the matter genuinely requires."] },
      { heading: "Your Choices", paragraphs: ["You can ask whether a specific class was recorded and how that recording is handled at any time — we'll respond within a reasonable time. If you wish to withdraw consent for recording, you can do so at any point; this will never affect the quality of teaching your family receives."] },
      { heading: "Contact and Escalation", paragraphs: ["Questions about a recording can be sent to our official email or WhatsApp contact. Any concern that a recording was accessed or used inappropriately is escalated immediately to our Safeguarding Contact and Operations Lead."] },
    ],
  },
  "/complaints": {
    title: "Complaints Process", summary: "We want every family and adult learner to feel genuinely heard if something goes wrong. This page explains how to raise a concern with Tajweed Scholars and what happens after you do.",
    sections: [
      { heading: "What You Can Raise a Complaint About", paragraphs: ["Anything — a teaching concern, a scheduling or billing issue, a safeguarding worry, or general dissatisfaction with your experience. There is no concern too small to raise, and no concern is ever dismissed because a family has been with us a short or a long time."] },
      { heading: "How to Raise a Concern", paragraphs: ["Contact us through our official WhatsApp number, email, or the Contact page on our website. Please include the student's name, the programme or class involved, and a short description of the concern so we can look into it quickly."] },
      { heading: "What Happens Next", steps: ["Acknowledgement. We aim to acknowledge every complaint within one business day.", "Review. Your concern is reviewed by the relevant team — Admissions, Parent Success, or our Safeguarding Contact, depending on the nature of the issue.", "Response. We will follow up with a clear explanation, and where something needs to be put right — a rescheduled class, a credit, a teacher change, or another resolution — we will confirm the next step directly with you.", "Escalation. If you're not satisfied with the response, or the matter is more serious, it is escalated to the Tajweed Scholars Operations Lead for a final review."] },
      { heading: "Safeguarding Concerns", paragraphs: ["If your concern relates to a child's safety or wellbeing, please say so clearly when you contact us, or use the safeguarding contact route described in our Child Safeguarding Policy. Safeguarding concerns are always treated with urgency, ahead of routine queries."] },
      { heading: "Contact and Escalation", paragraphs: ["All complaints and concerns can be raised through our official WhatsApp number, email, or Contact page. Unresolved matters are escalated to the Operations Lead / Founder for a final decision."] },
    ],
  },
  "/acceptable-use": {
    title: "Acceptable Use Policy", summary: "This policy sets out how Tajweed Scholars' live classes, communication channels, and website should be used, so every family, student, and teacher has a safe, respectful, and reliable experience.",
    sections: [
      { heading: "Who This Applies To", paragraphs: ["This applies to every parent, student, and adult learner using any Tajweed Scholars service — live classes over Zoom, our official WhatsApp and email channels, and our website."] },
      { heading: "Expected Use of Live Classes", bullets: ["Join classes from a quiet, appropriate space, ready to participate.", "Treat your teacher, and any other Tajweed Scholars staff, with courtesy and respect at all times.", "Do not record, screenshot, or share a live class beyond what is provided directly by Tajweed Scholars, without prior written permission.", "Do not use class time for any purpose unrelated to the lesson being taught."] },
      { heading: "Expected Use of Communication Channels", bullets: ["Use only our official WhatsApp number and email for all communication with Tajweed Scholars — this protects both your family and your teacher.", "Do not contact a teacher through a personal number or personal social media account, and do not ask a teacher to do so, even if it feels more convenient.", "Keep communication respectful. Abusive, threatening, or discriminatory language toward any teacher or staff member will not be tolerated and may result in suspension of services."] },
      { heading: "Use of Our Website", bullets: ["Use the website only for its intended purpose — learning about our programmes, booking a trial, and managing your account.", "Do not attempt to access, copy, or misuse any part of the website or its content beyond ordinary use."] },
      { heading: "What Happens If This Policy Isn't Followed", paragraphs: ["Where conduct falls short of this policy, we will first raise the concern directly and try to resolve it constructively. In cases of serious or repeated misconduct — particularly anything affecting the safety or wellbeing of a child or a teacher — Tajweed Scholars reserves the right to suspend or end services for the family or individual concerned."] },
      { heading: "Contact and Escalation", paragraphs: ["Questions about this policy, or a concern about how it's being applied, can be raised through our official WhatsApp number, email, or Contact page. Unresolved concerns are escalated to the Operations Lead / Founder."] },
    ],
  },
};
