import React from "react";
import { Icon } from "../Icon";
import { Link } from "../../lib/router";
const trials = [
  { title: "Trial 1 · Placement & mini-lesson", text: "The teacher confirms the starting level and delivers a real mini-lesson.", icon: "UserCheck" },
  { title: "Trial 2 · Full learning experience", text: "A complete lesson includes correction, guided practice, and encouraging feedback.", icon: "BookOpen" },
  { title: "Trial 3 · Recap & recommendation", text: "A final lesson, progress recap, and no-pressure enrollment recommendation.", icon: "ClipboardList" }
];
export const VisualTrialJourney: React.FC = () => <section className="border-y border-stone-200 bg-white py-10 sm:py-14" aria-labelledby="trials-title"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-bold text-emerald-800">Your three-class trial</p><h2 id="trials-title" className="mt-2 text-3xl font-bold sm:text-4xl">Experience real teaching before you enroll.</h2><p className="mt-3 text-stone-600">All three trial classes are free. No payment information is required.</p></div><ol className="mt-7 grid gap-4 md:grid-cols-3">{trials.map((trial, i) => <li key={trial.title} className="rounded-xl border border-stone-200 bg-stone-50 p-5"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-emerald-800 text-white"><Icon name={trial.icon} size={19}/></span><p className="mt-4 text-xs font-bold text-emerald-800">Trial {i + 1} of 3</p><h3 className="mt-1 text-lg font-bold">{trial.title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{trial.text}</p></li>)}</ol><div className="mt-6 text-center"><Link to="/free-trial" className="inline-flex min-h-12 items-center rounded-lg bg-emerald-800 px-6 text-sm font-bold text-white">Book 3 Free Trial Classes</Link></div></div></section>;
