import React, { useCallback, useEffect, useRef, useState } from "react";
import { Link, useRouter } from "../lib/router";
import { NAVIGATION_LINKS } from "../config/site";
import { Icon } from "./Icon";
import { useDismissibleOverlay } from "../lib/useDismissibleOverlay";

export const Header: React.FC = () => {
  // Stable accessibility/test identifiers: mobile-programs and mobile-policies.
  const { path, navigate } = useRouter();
  const [drawer, setDrawer] = useState(false), [programs, setPrograms] = useState(false), [policies, setPolicies] = useState(false), [desktopPrograms, setDesktopPrograms] = useState(false);
  const drawerPanel = useRef<HTMLDivElement>(null), drawerButton = useRef<HTMLButtonElement>(null), desktopRoot = useRef<HTMLDivElement>(null), desktopButton = useRef<HTMLButtonElement>(null);
  const closeDrawer = useCallback(() => { setDrawer(false); setPrograms(false); setPolicies(false); }, []);
  const closeDesktop = useCallback(() => setDesktopPrograms(false), []);
  useDismissibleOverlay({ open: desktopPrograms, onClose: closeDesktop, rootRef: desktopRoot, triggerRef: desktopButton });
  useDismissibleOverlay({ open: drawer, onClose: closeDrawer, rootRef: drawerPanel, triggerRef: drawerButton });
  useEffect(() => { closeDrawer(); closeDesktop(); document.body.style.overflow = ""; }, [path, closeDrawer, closeDesktop]);
  useEffect(() => { if (!drawer) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previous; }; }, [drawer]);
  const nav = (to: string) => { closeDrawer(); closeDesktop(); navigate(to); };
  const link = (label: string, to: string) => <Link to={to} className="flex min-h-11 items-center rounded-md font-semibold text-stone-700 hover:text-emerald-800">{label}</Link>;
  return <><header id="app-header" className="sticky top-0 z-50 border-b border-stone-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-[74px] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
    <Link to="/" aria-label="Tajweed Scholars home"><img src="/brand/logo-horizontal.svg" alt="Tajweed Scholars" width="225" height="50" decoding="async" className="h-auto w-[210px] lg:w-[225px]" /></Link>
    <nav className="hidden items-center gap-5 text-sm lg:flex" aria-label="Main navigation">{link("Home", "/")}<div ref={desktopRoot} className="relative flex items-center"><Link to="/programs" onClick={closeDesktop} className="flex min-h-11 items-center font-semibold text-stone-700 hover:text-emerald-800">Programs</Link><button ref={desktopButton} type="button" aria-label="Open Programs submenu" aria-expanded={desktopPrograms} onClick={event => { event.stopPropagation(); setDesktopPrograms(value => !value); }} className="flex h-11 w-8 items-center justify-center"><Icon name="ChevronDown" size={14} /></button>{desktopPrograms && <div className="absolute left-1/2 top-full w-64 -translate-x-1/2 rounded-xl border bg-white p-2 shadow-xl"><Link to="/programs" onClick={closeDesktop} className="flex min-h-11 items-center rounded-lg px-3 text-sm font-bold hover:bg-emerald-50">All Programs</Link>{NAVIGATION_LINKS.programs.map(item => <Link key={item.path} to={item.path} onClick={closeDesktop} className="flex min-h-11 items-center rounded-lg px-3 text-sm hover:bg-emerald-50">{item.label}</Link>)}</div>}</div>{link("Why Us", "/why-choose-us")}{link("Pricing", "/pricing")}{link("About", "/about")}{link("Contact", "/contact")}</nav>
    <button type="button" onClick={() => nav("/free-trial")} className="hidden min-h-11 rounded-lg bg-emerald-800 px-4 text-sm font-bold text-white lg:block">Book 3 Free Trial Classes</button><button ref={drawerButton} type="button" onClick={() => setDrawer(true)} aria-expanded={drawer} aria-controls="mobile-navigation" aria-label="Open navigation menu" className="flex h-11 w-11 items-center justify-center lg:hidden"><Icon name="Menu" /></button>
  </div></header>{drawer && <div className="fixed inset-0 z-[70] lg:hidden"><button type="button" aria-label="Close navigation menu" onClick={closeDrawer} className="absolute inset-0 bg-stone-950/45" /><div ref={drawerPanel} id="mobile-navigation" role="dialog" aria-modal="true" aria-label="Navigation menu" className="absolute right-0 top-0 flex h-[100dvh] w-[min(88vw,22rem)] flex-col bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-4"><strong className="text-xl">Menu</strong><button type="button" onClick={closeDrawer} aria-label="Close navigation menu" className="flex h-11 w-11 items-center justify-center"><Icon name="X" /></button></div><nav className="min-h-0 flex-1 overflow-y-auto px-4 py-2" aria-label="Mobile navigation"><Link to="/" onClick={closeDrawer} className="flex min-h-12 items-center border-b font-semibold">Home</Link><div className="flex border-b"><Link to="/programs" onClick={closeDrawer} className="flex min-h-12 flex-1 items-center font-semibold">Programs</Link><button type="button" aria-label="Expand Programs submenu" aria-expanded={programs} onClick={() => { setPrograms(v => !v); setPolicies(false); }} className="flex h-12 w-12 items-center justify-center"><Icon name="ChevronDown" className={programs ? "rotate-180" : ""} /></button></div>{programs && <div className="border-b bg-stone-50 px-2">{NAVIGATION_LINKS.programs.map(item => <Link key={item.path} to={item.path} onClick={closeDrawer} className="flex min-h-11 items-center px-2 text-sm">{item.label}</Link>)}</div>}{[["Why Choose Us","/why-choose-us"],["Pricing","/pricing"],["About","/about"],["Contact","/contact"]].map(([label,to]) => <Link key={to} to={to} onClick={closeDrawer} className="flex min-h-12 items-center border-b font-semibold">{label}</Link>)}<div className="flex border-b"><Link to="/privacy-policy" onClick={closeDrawer} className="flex min-h-12 flex-1 items-center font-semibold">Policies</Link><button type="button" aria-label="Expand Policies submenu" aria-expanded={policies} onClick={() => { setPolicies(v => !v); setPrograms(false); }} className="flex h-12 w-12 items-center justify-center"><Icon name="ChevronDown" className={policies ? "rotate-180" : ""} /></button></div>{policies && <div className="bg-stone-50 px-2">{NAVIGATION_LINKS.policies.map(item => <Link key={item.path} to={item.path} onClick={closeDrawer} className="flex min-h-11 items-center px-2 text-sm">{item.label}</Link>)}</div>}</nav><div className="border-t p-4"><button type="button" onClick={() => nav("/free-trial")} className="min-h-12 w-full rounded-lg bg-emerald-800 px-4 text-sm font-bold text-white">Book 3 Free Trial Classes</button></div></div></div>}</>;
};
