import React, { useCallback, useId, useMemo, useRef, useState } from "react";
import flags from "react-phone-number-input/flags";
import { getCountryCallingCode, type Country } from "react-phone-number-input";
import { Check, ChevronDown, Globe2 } from "lucide-react";
import { POPULAR_COUNTRY_CODES } from "../lib/trialUx";
import { useDismissibleOverlay } from "../lib/useDismissibleOverlay";

export type PhoneCountryOption = { code: Country; name: string; group?: string };
export function CountryFlag({ country, countryName }: { country?: Country; countryName: string }) {
  if (!country) return <span className="inline-flex h-[18px] w-6 shrink-0 items-center justify-center overflow-hidden rounded-sm"><Globe2 aria-hidden="true" className="h-5 w-5" /></span>;
  const Flag = flags[country];
  return Flag ? <span data-country-flag className="inline-flex h-[18px] w-6 shrink-0 items-center justify-center overflow-hidden rounded-sm border border-stone-200 [&>svg]:block [&>svg]:h-full [&>svg]:w-full" title={countryName}><Flag title="" /></span> : <Globe2 aria-hidden="true" className="h-5 w-5 shrink-0" />;
}

export function PhoneCountrySelect({ country, options, onChange, initialOpen = false, inputRef }: { country?: Country; options: PhoneCountryOption[]; onChange: (country: Country) => void; initialOpen?: boolean; inputRef?: React.RefObject<HTMLInputElement | null> }) {
  const id = `${useId()}-phone-countries`, button = useRef<HTMLButtonElement>(null), root = useRef<HTMLDivElement>(null), search = useRef<HTMLInputElement>(null);
  const [open, setOpen] = useState(initialOpen), [query, setQuery] = useState(""), [active, setActive] = useState(0);
  const selected = options.find(option => option.code === country);
  const close = useCallback((focusInput = false) => { setOpen(false); setQuery(""); setActive(0); requestAnimationFrame(() => focusInput ? (inputRef?.current || button.current)?.focus() : button.current?.focus()); }, [inputRef]);
  const dismiss = useCallback(() => close(false), [close]);
  useDismissibleOverlay({ open, onClose: dismiss, rootRef: root, triggerRef: button });
  const grouped = useMemo(() => { const filtered = options.filter(option => `${option.name} ${option.code} +${getCountryCallingCode(option.code)}`.toLowerCase().includes(query.toLowerCase())); const used = new Set<Country>(); const take = (codes: readonly Country[], group: string) => codes.flatMap(code => { const item = filtered.find(option => option.code === code); if (!item || used.has(code)) return []; used.add(code); return [{ ...item, group }]; }); return [...take(country ? [country] : [], "Recommended"), ...take(POPULAR_COUNTRY_CODES, "Popular"), ...filtered.filter(option => !used.has(option.code)).map(option => ({ ...option, group: "All countries" }))]; }, [country, options, query]);
  const choose = (code: Country) => { onChange(code); close(true); };
  const show = () => { setOpen(true); setQuery(""); setActive(0); requestAnimationFrame(() => search.current?.focus()); };
  return <div ref={root} className="relative h-12 w-[72px] shrink-0"><button ref={button} type="button" aria-label={`Change WhatsApp country, currently ${selected?.name || "none selected"}`} aria-haspopup="listbox" aria-expanded={open} aria-controls={id} onClick={event => { event.stopPropagation(); open ? close() : show(); }} className="flex h-12 min-h-11 w-[72px] shrink-0 items-center justify-center gap-2 px-2"><CountryFlag country={country} countryName={selected?.name || ""} /><ChevronDown aria-hidden="true" className="h-4 w-4 shrink-0" /></button>{open && <div className="absolute left-0 z-50 mt-1 w-[min(19rem,calc(100vw-2rem))] overflow-hidden rounded-lg border bg-white shadow-xl" onClick={event => event.stopPropagation()}><div className="p-2"><input ref={search} autoFocus value={query} onChange={event => { setQuery(event.target.value); setActive(0); }} onKeyDown={event => { if (event.key === "ArrowDown") { event.preventDefault(); setActive(current => Math.min(current + 1, grouped.length - 1)); } else if (event.key === "ArrowUp") { event.preventDefault(); setActive(current => Math.max(current - 1, 0)); } else if (event.key === "Enter" && grouped[active]) { event.preventDefault(); event.stopPropagation(); choose(grouped[active].code); } else if (event.key === "Escape") { event.preventDefault(); event.stopPropagation(); close(); } }} aria-label="Search phone countries" role="combobox" aria-expanded="true" aria-controls={id} aria-activedescendant={grouped[active] ? `${id}-${grouped[active].code}` : undefined} placeholder="Search country or calling code" className="min-h-11 w-full rounded-md border px-3 text-sm" /></div><ul id={id} role="listbox" className="max-h-[min(18rem,50vh)] overflow-auto p-1">{grouped.map((option, index) => <React.Fragment key={option.code}>{option.group !== grouped[index - 1]?.group && <li role="presentation" className="px-3 pb-1 pt-3 text-xs font-bold text-stone-500">{option.group}</li>}<li id={`${id}-${option.code}`} role="option" aria-selected={option.code === country} onPointerMove={() => setActive(index)} onPointerDown={event => { event.preventDefault(); event.stopPropagation(); choose(option.code); }} className={`flex min-h-11 cursor-pointer items-center gap-3 rounded-md px-3 text-sm ${active === index ? "bg-emerald-50" : "hover:bg-emerald-50"}`}><CountryFlag country={option.code} countryName={option.name} /><span className="min-w-0 flex-1 truncate">{option.name}</span><span className="shrink-0 tabular-nums">+{getCountryCallingCode(option.code)}</span>{option.code === country && <Check aria-label="Selected" className="h-4 w-4 shrink-0 text-emerald-700" />}</li></React.Fragment>)}</ul></div>}</div>;
}
