import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";
import { Icon } from "./Icon";
import { useRouter } from "../lib/router";
import { CHILD_AGES, programFinderQuery, programFinderRecommendation, type FinderAudience } from "../lib/programFinderMapping";

const FinderContext = createContext<{ openFinder: (trigger?: HTMLElement | null) => void; open: boolean } | null>(null);
export const useProgramFinder = () => { const value = useContext(FinderContext); if (!value) throw new Error("useProgramFinder must be used inside ProgramFinderProvider"); return value; };
const audiences = [{ id: "child" as const, label: "My child / another learner" }, { id: "adult" as const, label: "Myself" }, { id: "advanced" as const, label: "Tajweed or Hifz focus" }];
const answers: Record<FinderAudience, { value: string; label: string }[]> = {
  child: CHILD_AGES.map(value => ({ value, label: value === "adult" ? "Adult" : value.replace("-", "–") })),
  adult: [{ value: "beginner", label: "Starting from the beginning" }, { value: "reading", label: "Improve Quran reading" }, { value: "tajweed", label: "Improve Tajweed" }, { value: "hifz", label: "Memorize Quran" }],
  advanced: [{ value: "tajweed", label: "Tajweed correction" }, { value: "hifz", label: "Hifz" }, { value: "both", label: "Both" }]
};

export function ProgramFinderProvider({ children }: { children: React.ReactNode }) {
  const { navigate } = useRouter(); const [open, setOpen] = useState(false); const [audience, setAudience] = useState<FinderAudience>(); const [answer, setAnswer] = useState<string>();
  const dialog = useRef<HTMLDivElement>(null), closeButton = useRef<HTMLButtonElement>(null), opener = useRef<HTMLElement | null>(null);
  const recommendation = useMemo(() => audience && answer ? programFinderRecommendation(audience, answer) : undefined, [audience, answer]);
  const dismiss = (restore = true) => { setOpen(false); setAudience(undefined); setAnswer(undefined); if (restore) requestAnimationFrame(() => opener.current?.focus()); };
  const go = (to: string) => { dismiss(false); navigate(to); };
  useEffect(() => { window.dispatchEvent(new CustomEvent("program-finder-visibility", { detail: { open } })); if (!open) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; closeButton.current?.focus(); const key = (e: KeyboardEvent) => { if (e.key === "Escape") dismiss(); if (e.key === "Tab" && dialog.current) { const items = [...dialog.current.querySelectorAll<HTMLElement>("button,a[href]")]; const first = items[0], last = items.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }; addEventListener("keydown", key); return () => { removeEventListener("keydown", key); document.body.style.overflow = previous; }; }, [open]);
  return <FinderContext.Provider value={{ open, openFinder: trigger => { opener.current = trigger || document.activeElement as HTMLElement; setOpen(true); } }}>{children}{open && <div className="fixed inset-0 z-[90] flex items-end justify-center sm:items-center sm:p-4"><button type="button" aria-label="Close program finder" onClick={() => dismiss()} className="absolute inset-0 bg-stone-950/50"/><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="program-finder-title" className="relative z-10 max-h-[88dvh] w-full overflow-y-auto rounded-t-2xl bg-white p-5 shadow-2xl sm:max-w-lg sm:rounded-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-emerald-800">Program recommendation</p><h2 id="program-finder-title" className="mt-1 text-2xl font-bold">Find My Program</h2></div><button ref={closeButton} type="button" onClick={() => dismiss()} aria-label="Close program finder" className="flex h-11 w-11 items-center justify-center"><Icon name="X"/></button></div>
  {!audience && <div className="mt-5"><p className="text-sm font-bold">1. Choose learner</p><div className="mt-3 grid gap-2">{audiences.map(item => <button key={item.id} type="button" onClick={() => setAudience(item.id)} className="min-h-12 rounded-lg border border-stone-300 p-3 text-left font-bold hover:border-emerald-700 hover:bg-emerald-50">{item.label}</button>)}</div></div>}
  {audience && !answer && <div className="mt-5"><p className="text-sm font-bold">2. Choose age or learning goal</p><div className="mt-3 grid gap-2">{answers[audience].map(item => <button key={item.value} type="button" onClick={() => setAnswer(item.value)} className="min-h-12 rounded-lg border border-stone-300 p-3 text-left font-semibold hover:border-emerald-700 hover:bg-emerald-50">{item.label}</button>)}</div><button type="button" onClick={() => setAudience(undefined)} className="mt-3 min-h-11 font-bold text-emerald-800">Back</button></div>}
  {audience && answer && recommendation && <div className="mt-5"><p className="text-sm font-bold">3. Recommendation</p><div className="mt-3 rounded-xl bg-emerald-50 p-4"><h3 className="text-xl font-bold text-emerald-950">{recommendation.title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{recommendation.explanation}</p></div><div className="mt-4 grid gap-2">{recommendation.route && <button type="button" onClick={() => go(recommendation.route!)} className="min-h-12 rounded-lg border border-emerald-700 px-4 font-bold text-emerald-800">View Recommended Program</button>}<button type="button" onClick={() => go(`/free-trial?${programFinderQuery(audience, answer)}`)} className="min-h-12 rounded-lg bg-emerald-800 px-4 font-bold text-white">Book 3 Free Trial Classes</button><button type="button" onClick={() => setAnswer(undefined)} className="min-h-11 font-bold text-emerald-800">Back</button><button type="button" onClick={() => { setAudience(undefined); setAnswer(undefined); }} className="min-h-11 text-sm font-semibold text-stone-600">Start Again</button></div></div>}</div></div>}</FinderContext.Provider>;
}
