import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { HighlightedLabel } from "./SearchCombobox.tsx";
import { readFileSync } from "node:fs";

const country = renderToStaticMarkup(<HighlightedLabel label="Pakistan" query="Pak" />);
const zone = renderToStaticMarkup(<HighlightedLabel label="Pakistan Time — Karachi (UTC+05:00)" query="Karachi" />);
assert.match(country, /<mark[^>]*>Pak<\/mark>istan/);
assert.match(country, /aria-label="Pakistan"/);
assert.match(zone, /<mark[^>]*>Karachi<\/mark>/);
assert.doesNotMatch(country, /dangerouslySetInnerHTML/);
const source = readFileSync(new URL("./SearchCombobox.tsx", import.meta.url), "utf8");
assert.match(source, /absolute left-0 top-full z-50/);
assert.doesNotMatch(source, /Detected|Suggested from your device/);
assert.match(source, /name=\{searchName\}/);
assert.match(source, /"ts-country-filter"/);
assert.match(source, /"ts-timezone-filter"/);
assert.match(source, /autoComplete="off"/);
assert.match(source, /autoCapitalize="none"/);
assert.match(source, /spellCheck=\{false\}/);
assert.match(source, /role="combobox"/);
assert.match(source, /aria-autocomplete="list"/);
assert.match(source, /event\.key === "Escape"/);
assert.match(source, /document\.addEventListener\("pointerdown", outside\)/);
assert.match(source, /onClick=\{\(\) => open \? close\(\) : show\(\)\}/);
assert.match(source, /onClick=\{\(\) => choose\(option\)\}/);
assert.match(source, /close\(true\)/);
assert.doesNotMatch(source, /in-flow|static z-/);
const trialFormSource = readFileSync(new URL("./TrialForm.tsx", import.meta.url), "utf8");
assert.doesNotMatch(trialFormSource, />Change</);
assert.match(trialFormSource, /You can change this at any time\./);
console.log("search match highlighting tests passed");
