import React, { useEffect, useMemo, useRef, useState } from "react";
import RawPhoneInput, { getCountries, isPossiblePhoneNumber, parsePhoneNumber, type Country } from "react-phone-number-input";
import countryLabels from "react-phone-number-input/locale/en";
import "react-phone-number-input/style.css";
import { Icon } from "./Icon";
import { submitTrialRequest, TrialSubmissionError, type TrialSubmissionPayload } from "../lib/trialSubmission";
import { AGE_GROUP_OPTIONS, LEARNER_TYPE_OPTIONS, MAIN_GOAL_OPTIONS, PREFERRED_DAY_OPTIONS, PREFERRED_TIME_OPTIONS, UNDER_18_AGE_GROUPS, type AgeGroup, type LearnerType, type MainGoal, type PreferredDay, type PreferredTime } from "../shared/trialOptions";
import { SITE_CONFIG } from "../config/site";
import { Link } from "../lib/router";

type FormData = { learnerType: LearnerType | ""; ageGroup: AgeGroup | ""; mainGoal: MainGoal | ""; contactName: string; guardianName: string; countryCode: Country | ""; countryName: string; region: string; timeZone: string; whatsapp: string; email: string; preferredDays: PreferredDay[]; preferredTime: PreferredTime | ""; notes: string; consent: boolean };
type Field = keyof FormData; type Errors = Partial<Record<Field, string>>;
const initial: FormData = { learnerType: "", ageGroup: "", mainGoal: "", contactName: "", guardianName: "", countryCode: "", countryName: "", region: "", timeZone: "", whatsapp: "", email: "", preferredDays: [], preferredTime: "", notes: "", consent: false };
const countries = getCountries().map((code) => ({ code, name: countryLabels[code] })).sort((a, b) => a.name.localeCompare(b.name));
const commonDomains = ["gmail.com", "outlook.com", "hotmail.com", "yahoo.com", "icloud.com"];
const PhoneInput = (props: React.ComponentProps<typeof RawPhoneInput>) => <RawPhoneInput {...props} international withCountryCallingCode />;
const validEmail = (value: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const validZone = (value: string) => { try { new Intl.DateTimeFormat(undefined, { timeZone: value }).format(); return true; } catch { return false; } };
const emailSuggestion = (email: string) => { const domain = email.toLowerCase().split("@")[1]; if (!domain) return ""; const typo: Record<string, string> = { "gmial.com": "gmail.com", "gamil.com": "gmail.com", "gmail.con": "gmail.com", "hotnail.com": "hotmail.com", "outlok.com": "outlook.com", "yaho.com": "yahoo.com" }; return typo[domain] || ""; };

function safePrefill(): Partial<FormData> {
  const query = window.location.hash.split("?")[1]; if (!query) return {}; const p = new URLSearchParams(query); const result: Partial<FormData> = {};
  const learners: Record<string, LearnerType> = { "My Child": "child", "My child": "child", Myself: "self", child: "child", self: "self" };
  const ages: Record<string, AgeGroup> = { "4–5": "4-6", "4–6": "4-6", "4-6": "4-6", "6–8": "7-9", "7–9": "7-9", "7-9": "7-9", "9–12": "10-12", "10–12": "10-12", "10-12": "10-12", "13–15": "13-15", "13-15": "13-15", "16–17": "16-17", "16-17": "16-17", Adult: "adult", adult: "adult" };
  const goals: Record<string, MainGoal> = { "Learn from the beginning": "qaida", "Learn Qaida": "qaida", "Improve Quran reading": "quran-reading", "Improve Tajweed": "tajweed", "Tajweed correction": "tajweed", "Memorize Quran": "hifz", Hifz: "hifz", "Not sure yet": "unsure" };
  const programs: Record<string, MainGoal> = { "Kids Quran Classes": "unsure", "Adult Quran Classes": "unsure", "Tajweed Course": "tajweed", "Hifz Program": "hifz" };
  const learner = p.get("learnerType"), age = p.get("ageGroup"), goal = p.get("goal"), program = p.get("recommendedProgram");
  if (learner && learners[learner]) result.learnerType = learners[learner]; if (age && ages[age]) result.ageGroup = ages[age];
  if (goal && goals[goal]) result.mainGoal = goals[goal]; else if (program && programs[program]) result.mainGoal = programs[program];
  return result;
}
const ErrorText = ({ field, errors }: { field: Field; errors: Errors }) => errors[field] ? <p id={`${field}-error`} className="mt-1.5 flex items-center gap-1 text-xs font-semibold text-red-700"><Icon name="AlertCircle" size={14} />{errors[field]}</p> : null;

export const TrialForm: React.FC = () => {
  const [step, setStep] = useState(1), [data, setData] = useState<FormData>(initial), [errors, setErrors] = useState<Errors>({});
  const [status, setStatus] = useState<"idle" | "submitting" | "success" | "error">("idle"), [message, setMessage] = useState(""), [leadId, setLeadId] = useState(""), [honeypot, setHoneypot] = useState("");
  const headingRef = useRef<HTMLHeadingElement>(null), submissionId = useRef(globalThis.crypto.randomUUID()), formStartedAt = useRef(Date.now()), submitting = useRef(false);
  const isMinor = data.ageGroup !== "" && UNDER_18_AGE_GROUPS.includes(data.ageGroup as AgeGroup);
  const zones = useMemo(() => { try { return (Intl as typeof Intl & { supportedValuesOf?: (key: string) => string[] }).supportedValuesOf?.("timeZone") || []; } catch { return []; } }, []);
  const suggestion = emailSuggestion(data.email);
  useEffect(() => { let timeZone = ""; try { timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone; } catch { /* editable fallback */ } setData((v) => ({ ...v, ...safePrefill(), timeZone })); }, []);
  const update = <K extends Field>(field: K, value: FormData[K]) => { setData((v) => ({ ...v, [field]: value })); if (errors[field]) setErrors((v) => ({ ...v, [field]: undefined })); };
  const reveal = (node: HTMLElement | null) => { node?.scrollIntoView({ behavior: "smooth", block: "center" }); node?.focus({ preventScroll: true }); };
  const showErrors = (next: Errors) => { setErrors(next); const first = Object.keys(next)[0]; requestAnimationFrame(() => reveal(document.getElementById(first))); };
  const validate = (forStep: number) => { const e: Errors = {};
    if (forStep === 1) { if (!data.learnerType) e.learnerType = "Choose who is learning."; if (!data.ageGroup) e.ageGroup = "Choose an age group."; if (!data.mainGoal) e.mainGoal = "Choose the main goal."; }
    if (forStep === 2) { if (!data.contactName.trim()) e.contactName = "Enter the parent or learner name."; if (isMinor && !data.guardianName.trim()) e.guardianName = "Enter a parent or guardian name."; if (!data.countryCode) e.countryName = "Choose a country from the list."; if (!data.timeZone.trim() || !validZone(data.timeZone.trim())) e.timeZone = "Enter a valid IANA time zone."; if (!data.whatsapp || !isPossiblePhoneNumber(data.whatsapp)) e.whatsapp = "Enter a possible international phone number."; else if (parsePhoneNumber(data.whatsapp)?.country !== data.countryCode) e.whatsapp = "The phone number country must match the selected country."; const email = data.email.trim().toLowerCase(); if (!validEmail(email)) e.email = "Enter a valid email address."; }
    if (forStep === 3) { if (!data.preferredDays.length) e.preferredDays = "Choose at least one preferred day."; if (!data.preferredTime) e.preferredTime = "Choose a preferred time."; if (data.notes.length > 1000) e.notes = "Notes must be 1000 characters or fewer."; if (!data.consent) e.consent = "Consent is required."; } return e;
  };
  const showStep = (value: number) => { setStep(value); setErrors({}); requestAnimationFrame(() => reveal(headingRef.current)); };
  const next = () => { const e = validate(step); if (Object.keys(e).length) showErrors(e); else showStep(step + 1); };
  const chooseCountry = (name: string) => { const match = countries.find((country) => country.name.toLowerCase() === name.trim().toLowerCase()); setData((v) => ({ ...v, countryName: name, countryCode: match?.code || "", whatsapp: match && v.countryCode !== match.code ? "" : v.whatsapp })); setErrors((v) => ({ ...v, countryName: undefined, whatsapp: undefined })); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (submitting.current) return; const e = validate(3); if (Object.keys(e).length) return showErrors(e);
    const payload: TrialSubmissionPayload = { learnerType: data.learnerType as LearnerType, ageGroup: data.ageGroup as AgeGroup, mainGoal: data.mainGoal as MainGoal, contactName: data.contactName.trim(), guardianName: isMinor ? data.guardianName.trim() : "", countryCode: data.countryCode, countryName: countries.find((c) => c.code === data.countryCode)?.name || "", region: data.region.trim(), timeZone: data.timeZone.trim(), whatsapp: data.whatsapp, email: data.email.trim().toLowerCase(), preferredDays: data.preferredDays, preferredTime: data.preferredTime as PreferredTime, notes: data.notes.trim(), consent: true, submissionId: submissionId.current, honeypot, formStartedAt: formStartedAt.current };
    submitting.current = true; setStatus("submitting"); setMessage(""); try { const result = await submitTrialRequest(payload); setLeadId(result.leadId); setStatus("success"); }
    catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : "We could not submit your request."); if (error instanceof TrialSubmissionError && Object.keys(error.fieldErrors).length) { const map: Record<string, Field> = { countryCode: "countryName", countryName: "countryName", whatsapp: "whatsapp", notes: "notes", learnerType: "learnerType", ageGroup: "ageGroup", mainGoal: "mainGoal", contactName: "contactName", guardianName: "guardianName", region: "region", timeZone: "timeZone", email: "email", preferredDays: "preferredDays", preferredTime: "preferredTime", consent: "consent" }; const mapped: Errors = {}; Object.entries(error.fieldErrors).forEach(([key, value]) => { if (map[key]) mapped[map[key]] = value; }); const first = Object.keys(mapped)[0] as Field | undefined; setStep(first && ["learnerType", "ageGroup", "mainGoal"].includes(first) ? 1 : first && ["contactName", "guardianName", "countryName", "region", "timeZone", "whatsapp", "email"].includes(first) ? 2 : 3); setErrors(mapped); requestAnimationFrame(() => reveal(first ? document.getElementById(first) : headingRef.current)); } } finally { submitting.current = false; }
  };
  const described = (field: Field) => errors[field] ? `${field}-error` : undefined, input = (field: Field) => `mt-1.5 min-h-11 w-full rounded-lg border bg-white px-3 text-sm ${errors[field] ? "border-red-500" : "border-stone-300"}`, choice = (selected: boolean) => `flex min-h-11 cursor-pointer items-center gap-2 rounded-lg border px-2 text-xs font-semibold sm:px-3 sm:text-sm ${selected ? "border-emerald-700 bg-emerald-50 text-emerald-900" : "border-stone-300 bg-white text-stone-700"}`;
  if (status === "success") return <div id="trial-form-container" className="mx-auto w-full max-w-[760px] rounded-2xl border border-emerald-200 bg-white p-6 text-center shadow-sm sm:p-10" role="status"><Icon name="CheckCircle2" size={28} className="mx-auto text-emerald-800" /><h2 className="mt-4 text-2xl font-bold text-stone-800">Your trial request has been received.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-stone-600">We’ll review your preferred days and time zone, then contact you through WhatsApp or email to arrange Trial 1.</p><p className="mt-3 text-sm font-bold text-emerald-800">Lead reference: {leadId}</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/" className="inline-flex min-h-11 items-center justify-center rounded-lg border border-emerald-700 px-5 text-sm font-bold text-emerald-800">Return to Home</Link><a href={SITE_CONFIG.WHATSAPP_LINK} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-emerald-800 px-5 text-sm font-bold text-white">Message Tajweed Scholars</a></div></div>;
  const options = <T extends string>(items: readonly { value: T; label: string }[], field: "learnerType" | "ageGroup" | "mainGoal" | "preferredTime") => items.map((o, i) => <label key={o.value} className={choice(data[field] === o.value)}><input id={i === 0 ? field : undefined} type="radio" name={field} checked={data[field] === o.value} onChange={() => update(field, o.value as FormData[typeof field])} aria-describedby={described(field)} />{o.label}</label>);
  return <div id="trial-form-container" className="mx-auto w-full max-w-[760px] rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="sticky top-16 z-20 rounded-t-2xl border-b border-stone-200 bg-white/95 px-4 py-3"><div className="flex justify-between"><p className="text-xs font-bold text-emerald-800">Step {step} of 3</p><p className="text-xs text-stone-500">No payment information</p></div><div className="mt-2 grid grid-cols-3 gap-1">{[1,2,3].map((n) => <span key={n} className={`h-1.5 rounded-full ${n <= step ? "bg-emerald-700" : "bg-stone-200"}`} />)}</div></div>
    <form onSubmit={submit} noValidate className="p-4 pb-6 sm:p-6"><h2 ref={headingRef} tabIndex={-1} className="text-xl font-bold text-stone-800">{step === 1 ? "About the learner" : step === 2 ? "Contact details" : "Class availability"}</h2><p className="mt-1 text-sm text-stone-600">{step === 1 ? "Help us understand the right starting point." : step === 2 ? "Tell us how to reach you to arrange the classes." : "Choose general preferences; the final time is confirmed with you."}</p>
      {step === 1 && <div className="mt-6 space-y-6"><fieldset><legend className="text-sm font-bold">Who is learning? *</legend><div className="mt-2 grid grid-cols-2 gap-2">{options(LEARNER_TYPE_OPTIONS, "learnerType")}</div><ErrorText field="learnerType" errors={errors} /></fieldset><fieldset><legend className="text-sm font-bold">Age group *</legend><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">{options(AGE_GROUP_OPTIONS, "ageGroup")}</div><ErrorText field="ageGroup" errors={errors} /></fieldset><fieldset><legend className="text-sm font-bold">Main goal *</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{options(MAIN_GOAL_OPTIONS, "mainGoal")}</div><ErrorText field="mainGoal" errors={errors} /></fieldset></div>}
      {step === 2 && <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Parent or learner name *<input id="contactName" value={data.contactName} onChange={(e) => update("contactName", e.target.value)} className={input("contactName")} /><ErrorText field="contactName" errors={errors} /></label>{isMinor && <label className="text-sm font-bold">Parent/guardian name *<input id="guardianName" value={data.guardianName} onChange={(e) => update("guardianName", e.target.value)} className={input("guardianName")} /><ErrorText field="guardianName" errors={errors} /></label>}<label className="text-sm font-bold">Country *<input id="countryName" list="country-options" value={data.countryName} onChange={(e) => chooseCountry(e.target.value)} className={input("countryName")} autoComplete="country-name" /><datalist id="country-options">{countries.map((c) => <option key={c.code} value={c.name} />)}</datalist><ErrorText field="countryName" errors={errors} /></label><label className="text-sm font-bold">State / Province / Region (optional)<input id="region" value={data.region} maxLength={100} onChange={(e) => update("region", e.target.value)} className={input("region")} /><span className="mt-1 block text-xs font-normal text-stone-600">Helpful for countries with multiple time zones.</span><ErrorText field="region" errors={errors} /></label><label className="text-sm font-bold">Time zone *<input id="timeZone" list="time-zone-options" value={data.timeZone} onChange={(e) => update("timeZone", e.target.value)} className={input("timeZone")} placeholder="e.g. Asia/Karachi" /><datalist id="time-zone-options">{zones.map((z) => <option key={z} value={z} />)}</datalist><ErrorText field="timeZone" errors={errors} /></label><label className="text-sm font-bold">WhatsApp number *<PhoneInput id="whatsapp" international={false} defaultCountry={data.countryCode || undefined} country={data.countryCode || undefined} value={data.whatsapp || undefined} onChange={(value) => update("whatsapp", value || "")} className={`${input("whatsapp")} phone-input`} /><span className="mt-1 block text-xs font-normal text-stone-600">Use a number that can receive WhatsApp messages.</span><ErrorText field="whatsapp" errors={errors} /></label><label className="text-sm font-bold sm:col-span-2">Email address *<input id="email" type="email" value={data.email} onChange={(e) => update("email", e.target.value)} onBlur={() => update("email", data.email.trim().toLowerCase())} className={input("email")} autoComplete="email" />{suggestion && commonDomains.includes(suggestion) && <button type="button" className="mt-1 text-xs text-emerald-800 underline" onClick={() => update("email", `${data.email.split("@")[0]}@${suggestion}`)}>Did you mean {suggestion}?</button>}<ErrorText field="email" errors={errors} /></label></div>}
      {step === 3 && <div className="mt-6 space-y-6"><fieldset><legend className="text-sm font-bold">Preferred days *</legend><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{PREFERRED_DAY_OPTIONS.map((o, i) => <label key={o.value} className={choice(data.preferredDays.includes(o.value))}><input id={i === 0 ? "preferredDays" : undefined} type="checkbox" checked={data.preferredDays.includes(o.value)} onChange={() => update("preferredDays", data.preferredDays.includes(o.value) ? data.preferredDays.filter((v) => v !== o.value) : [...data.preferredDays, o.value])} />{o.label}</label>)}</div><ErrorText field="preferredDays" errors={errors} /></fieldset><fieldset><legend className="text-sm font-bold">Preferred general time *</legend><div className="mt-2 grid grid-cols-3 gap-2">{options(PREFERRED_TIME_OPTIONS, "preferredTime")}</div><ErrorText field="preferredTime" errors={errors} /></fieldset><label className="block text-sm font-bold">Optional note<textarea id="notes" value={data.notes} onChange={(e) => update("notes", e.target.value)} rows={3} className="mt-1.5 w-full rounded-lg border border-stone-300 p-3 text-sm font-normal" /><ErrorText field="notes" errors={errors} /></label><div><label className="flex min-h-11 cursor-pointer items-start gap-3 text-sm leading-6"><input id="consent" type="checkbox" checked={data.consent} onChange={(e) => update("consent", e.target.checked)} className="mt-1.5 h-5 w-5" />I agree that Tajweed Scholars may contact me about these trial classes through WhatsApp or email.</label><ErrorText field="consent" errors={errors} /></div></div>}
      <div className="absolute -left-[10000px] h-px w-px overflow-hidden" aria-hidden="true"><input name="website" value={honeypot} onChange={(e) => setHoneypot(e.target.value)} tabIndex={-1} autoComplete="off" /></div>{status !== "idle" && <div role="status" className={`mt-5 rounded-lg border p-3 text-sm ${status === "error" ? "border-red-300 bg-red-50 text-red-800" : "border-stone-200 bg-stone-50"}`}>{status === "submitting" ? "Submitting your request…" : message}</div>}<div className="mt-6 flex gap-3 border-t border-stone-200 pt-5">{step > 1 && <button type="button" onClick={() => showStep(step - 1)} className="min-h-11 rounded-lg border border-emerald-700 px-5 text-sm font-bold text-emerald-800">Back</button>}<button type={step === 3 ? "submit" : "button"} onClick={step === 3 ? undefined : next} disabled={status === "submitting"} className="min-h-12 flex-1 rounded-lg bg-emerald-800 px-4 text-sm font-bold text-white disabled:opacity-60">{step === 3 ? "Request My 3 Free Trial Classes" : "Continue"}</button></div></form></div>;
};
