import React, { useEffect, useMemo, useRef, useState } from "react";
import { getCountries, getCountryCallingCode, parsePhoneNumber, type Country } from "react-phone-number-input";
import countryLabels from "react-phone-number-input/locale/en";
import { Icon } from "./Icon";
import { submitTrialRequest, TrialSubmissionError } from "../lib/trialSubmission";
import { AGE_GROUP_OPTIONS, LEARNER_TYPE_OPTIONS, MAIN_GOAL_OPTIONS, PREFERRED_DAY_OPTIONS, PREFERRED_TIME_OPTIONS, type AgeGroup, type LearnerType, type MainGoal } from "../shared/trialOptions";
import { Link } from "../lib/router";
import { SearchCombobox } from "./SearchCombobox";
import { CountryFlag, PhoneCountrySelect } from "./PhoneCountrySelect";
import { addRecentIdentifier, getNationalPhonePlaceholder, getTimeZoneValues, groupTimeZones, learnerNameLabel, newSubmissionMeta, normalizePhoneEntry, orderCountries, readSessionIdentifiers, regionField, resolveDeviceDefaults, timeZoneLabel, writeSessionIdentifiers } from "../lib/trialUx";
import { requiresGuardian } from "../shared/trialOptions";
import { buildTrialSubmissionPayload, getVisibleErrors, nextLearnerData, stepForField, validateTrialForm, withLearnerType, type AttemptedSteps, type TrialErrors, type TrialField, type TrialFormData } from "../lib/trialFormLogic";

type FormData = TrialFormData; type Field = TrialField; type Errors = TrialErrors;
const initial: FormData = { learnerType: "", ageGroup: "", mainGoal: "", contactName: "", guardianName: "", countryCode: "", countryName: "", region: "", timeZone: "", whatsapp: "", email: "", preferredDays: [], preferredTime: "", notes: "", consent: false };
const countries = getCountries().map((code) => ({ code, name: countryLabels[code] })).sort((a, b) => a.name.localeCompare(b.name));
const commonDomains = ["gmail.com", "outlook.com", "hotmail.com", "yahoo.com", "icloud.com"];
const RECENT_COUNTRIES_KEY = "tajweed-trial-recent-countries", RECENT_ZONES_KEY = "tajweed-trial-recent-time-zones";
const emailSuggestion = (email: string) => { const domain = email.toLowerCase().split("@")[1]; if (!domain) return ""; const typo: Record<string, string> = { "gmial.com": "gmail.com", "gamil.com": "gmail.com", "gmail.con": "gmail.com", "hotnail.com": "hotmail.com", "outlok.com": "outlook.com", "yaho.com": "yahoo.com" }; return typo[domain] || ""; };

function safePrefill(): Partial<FormData> {
  const query = window.location.hash.split("?")[1]; if (!query) return {}; const p = new URLSearchParams(query); const result: Partial<FormData> = {};
  const learners: Record<string, LearnerType> = { "My Child": "child", "My child": "child", Myself: "self", child: "child", self: "self" };
  const ages: Record<string, AgeGroup> = { "4–5": "4-6", "4–6": "4-6", "4-6": "4-6", "6–8": "7-9", "7–9": "7-9", "7-9": "7-9", "9–12": "10-12", "10–12": "10-12", "10-12": "10-12", "13–15": "13-15", "13-15": "13-15", "16–17": "16-17", "16-17": "16-17", Adult: "adult", adult: "adult" };
  const goals: Record<string, MainGoal> = { qaida:"qaida", "quran-reading":"quran-reading", tajweed:"tajweed", hifz:"hifz", unsure:"unsure", "Learn from the beginning": "qaida", "Learn Qaida": "qaida", "Improve Quran reading": "quran-reading", "Improve Tajweed": "tajweed", "Tajweed correction": "tajweed", "Memorize Quran": "hifz", Hifz: "hifz", "Not sure yet": "unsure" };
  const programs: Record<string, MainGoal> = { "Kids Quran Classes": "unsure", "Adult Quran Classes": "unsure", "Tajweed Course": "tajweed", "Hifz Program": "hifz" };
  const learner = p.get("learnerType"), age = p.get("ageGroup"), goal = p.get("mainGoal") || p.get("goal"), program = p.get("recommendedProgram");
  if (learner && learners[learner]) result.learnerType = learners[learner]; if (age && ages[age]) result.ageGroup = ages[age];
  if (goal && goals[goal]) result.mainGoal = goals[goal]; else if (program && programs[program]) result.mainGoal = programs[program];
  return result;
}
const ErrorText = ({ field, errors }: { field: Field; errors: Errors }) => errors[field] ? <p id={`${field}-error`} className="mt-1.5 flex items-center gap-1 text-xs font-semibold text-red-700"><Icon name="AlertCircle" size={14} />{errors[field]}</p> : null;

const STEP_HEADINGS = ["Learner details", "Contact details", "Availability"] as const;
export function TrialProgress({ step }: { step: 1 | 2 | 3 }) {
  const current = `Step ${step} of 3 — ${STEP_HEADINGS[step - 1]}`;
  return <div className="sticky top-16 z-20 rounded-t-2xl border-b border-stone-200 bg-white/95 px-4 py-3" aria-label="Free Trial form progress">
    <div className="flex flex-wrap items-center justify-between gap-x-3 gap-y-1"><p aria-current="step" className="min-w-0 text-xs font-bold text-emerald-800">{current}</p><p className="shrink-0 text-[11px] text-stone-500 sm:text-xs">No payment information</p></div>
    <div className="mt-2 grid grid-cols-3 gap-1" role="progressbar" aria-label={current} aria-valuemin={1} aria-valuemax={3} aria-valuenow={step}>{[1, 2, 3].map((segment) => <span key={segment} aria-hidden="true" data-progress-state={segment <= step ? "complete" : "remaining"} className={`h-1.5 rounded-full ${segment <= step ? "bg-emerald-700" : "bg-stone-200"}`} />)}</div>
  </div>;
}

export const TrialForm: React.FC = () => {
  const [step, setStep] = useState(1), [data, setData] = useState<FormData>(initial), [errors, setErrors] = useState<Errors>({});
  const [attemptedSteps,setAttemptedSteps]=useState<AttemptedSteps>({1:false,2:false,3:false}),[apiErrorFields,setApiErrorFields]=useState<Set<Field>>(new Set());
  const [status, setStatus] = useState<"idle" | "submitting" | "success" | "error">("idle"), [message, setMessage] = useState(""), [leadId, setLeadId] = useState(""), [honeypot, setHoneypot] = useState(""), [phoneCountry, setPhoneCountry] = useState<Country | undefined>(), [phoneNational, setPhoneNational] = useState(""), [phoneCountryEdited, setPhoneCountryEdited] = useState(false), [keptContact, setKeptContact] = useState(false), [copied, setCopied] = useState(false), [detectedCountry, setDetectedCountry] = useState<Country | undefined>(), [detectedZone, setDetectedZone] = useState("UTC"), [recentCountries, setRecentCountries] = useState<Country[]>([]), [recentZones, setRecentZones] = useState<string[]>([]);
  const meta = useRef(newSubmissionMeta()), headingRef = useRef<HTMLHeadingElement>(null), submitting = useRef(false), copyResetTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null), activeLeadIdRef = useRef(leadId);
  const guardianRequired = requiresGuardian(data.ageGroup);
  const zones = useMemo(() => getTimeZoneValues(), []);
  const countryCodes = useMemo(() => new Set(countries.map(({ code }) => code)), []), zoneValues = useMemo(() => new Set(zones), [zones]);
  const countryOptions = useMemo(() => orderCountries(countries, detectedCountry, recentCountries), [detectedCountry, recentCountries]);
  const timeZoneOptions = useMemo(() => groupTimeZones(zones, detectedZone, data.countryCode || undefined, recentZones), [zones, detectedZone, data.countryCode, recentZones]);
  const regionMeta = regionField(data.countryCode || undefined);
  const suggestion = emailSuggestion(data.email);
  useEffect(() => { const defaults = resolveDeviceDefaults(navigator.languages?.length ? navigator.languages : [navigator.language]); setDetectedZone(defaults.timeZone); setDetectedCountry(defaults.country); setData((v) => ({ ...v, ...safePrefill(), timeZone: defaults.timeZone, ...(defaults.country ? { countryCode: defaults.country, countryName: countryLabels[defaults.country] } : {}) })); setPhoneCountry(defaults.phoneCountry); }, []);
  useEffect(() => { setRecentCountries(readSessionIdentifiers(RECENT_COUNTRIES_KEY, countryCodes) as Country[]); setRecentZones(readSessionIdentifiers(RECENT_ZONES_KEY, zoneValues)); }, [countryCodes, zoneValues]);
  useEffect(() => { activeLeadIdRef.current = leadId; if (copyResetTimerRef.current) clearTimeout(copyResetTimerRef.current); copyResetTimerRef.current = null; setCopied(false); }, [leadId]);
  useEffect(() => () => { if (copyResetTimerRef.current) clearTimeout(copyResetTimerRef.current); }, []);
  const update = <K extends Field>(field: K, value: FormData[K]) => { setData((v) => ({ ...v, [field]: value })); if (errors[field]) setErrors((v) => ({ ...v, [field]: undefined })); if (status === "error") { setStatus("idle"); setMessage(""); } };
  const reveal = (node: HTMLElement | null) => { node?.scrollIntoView({ behavior: "smooth", block: "center" }); node?.focus({ preventScroll: true }); };
  const showErrors = (next: Errors) => { setErrors(next); const first = Object.keys(next)[0]; requestAnimationFrame(() => reveal(document.getElementById(first))); };
  const showStep = (value: number) => { setStep(value); if(value===3)setAttemptedSteps(v=>({...v,3:false})); requestAnimationFrame(() => reveal(headingRef.current)); };
  const advanceCurrentStep = () => { const current = step as 1 | 2; setAttemptedSteps(v=>({...v,[current]:true})); setMessage(""); if (status === "error") setStatus("idle"); const nextErrors = validateTrialForm(data, current); if (Object.keys(nextErrors).length) return showErrors(nextErrors); showStep(current + 1); };
  const chooseCountry = (code: string) => { const match = countries.find((country) => country.code === code); if (!match) return; setData((v) => ({ ...v, countryName: match.name, countryCode: match.code })); if (!phoneCountryEdited) setPhoneCountry(match.code); setRecentCountries((current) => { const next = addRecentIdentifier(current, code, countryCodes) as Country[]; writeSessionIdentifiers(RECENT_COUNTRIES_KEY, next, countryCodes); return next; }); setErrors((v) => ({ ...v, countryName: undefined })); };
  const updatePhoneEntry = (value: string) => { const normalized = normalizePhoneEntry(value, phoneCountry); if (normalized.country && normalized.country !== phoneCountry) { setPhoneCountry(normalized.country); setPhoneCountryEdited(true); } setPhoneNational(normalized.national); update("whatsapp", normalized.e164); };
  const changePhoneCountry = (country: Country) => { setPhoneCountry(country); setPhoneCountryEdited(true); const normalized = normalizePhoneEntry(phoneNational, country); setPhoneNational(normalized.national); update("whatsapp", normalized.e164); };
  const submitFinalTrialRequest = async () => { if (submitting.current) return; setAttemptedSteps(v=>({...v,3:true})); setMessage(""); if (status === "error") setStatus("idle"); const payload = buildTrialSubmissionPayload({ ...data, countryName: countries.find((country) => country.code === data.countryCode)?.name || data.countryName }, { ...meta.current, honeypot }); const e = { ...validateTrialForm(data, "all"), ...validateTrialForm(payload, "all") }; if (Object.keys(e).length) { const first = Object.keys(e)[0] as Field; setAttemptedSteps(v=>({...v,[stepForField(first)]:true})); setStep(stepForField(first)); return showErrors(e); }
    submitting.current = true; setStatus("submitting"); setMessage(""); try { const result = await submitTrialRequest(payload); setLeadId(result.leadId); setStatus("success"); }
    catch (error) { setStatus("error"); setMessage(error instanceof TrialSubmissionError && Object.keys(error.fieldErrors).length ? "Please review the field highlighted below." : error instanceof Error ? error.message : "We could not submit your request."); if (error instanceof TrialSubmissionError && Object.keys(error.fieldErrors).length) { const map: Record<string, Field> = { countryCode: "countryName", countryName: "countryName", whatsapp: "whatsapp", notes: "notes", learnerType: "learnerType", ageGroup: "ageGroup", mainGoal: "mainGoal", contactName: "contactName", guardianName: "guardianName", region: "region", timeZone: "timeZone", email: "email", preferredDays: "preferredDays", preferredTime: "preferredTime", consent: "consent" }; const mapped: Errors = {}; Object.entries(error.fieldErrors).forEach(([key, value]) => { if (map[key]) mapped[map[key]] = value; }); const first = Object.keys(mapped)[0] as Field | undefined; setApiErrorFields(new Set(Object.keys(mapped) as Field[])); setStep(stepForField(first)); setErrors(mapped); requestAnimationFrame(() => reveal(first ? document.getElementById(first) : headingRef.current)); } } finally { submitting.current = false; }
  };
  const handleFormSubmit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (step < 3) { advanceCurrentStep(); return; } void submitFinalTrialRequest(); };
  const next = advanceCurrentStep;
  const submit = handleFormSubmit;
  const visibleErrors=getVisibleErrors(step as 1|2|3,errors,attemptedSteps,apiErrorFields); const described = (field: Field) => visibleErrors[field] ? `${field}-error` : undefined, input = (field: Field) => `mt-1.5 min-h-11 w-full rounded-lg border bg-white px-3 text-sm ${visibleErrors[field] ? "border-red-500" : "border-stone-300"}`, choice = (selected: boolean) => `flex min-h-11 cursor-pointer items-center gap-2 rounded-lg border px-2 text-xs font-semibold sm:px-3 sm:text-sm ${selected ? "border-emerald-700 bg-emerald-50 text-emerald-900" : "border-stone-300 bg-white text-stone-700"}`;
  const clearCopyTimer = () => { if (copyResetTimerRef.current) clearTimeout(copyResetTimerRef.current); copyResetTimerRef.current = null; };
  const copyReference = async () => { const copiedLeadId = leadId; clearCopyTimer(); await navigator.clipboard.writeText(copiedLeadId); if (activeLeadIdRef.current !== copiedLeadId) return; setCopied(true); copyResetTimerRef.current = setTimeout(() => { if (activeLeadIdRef.current === copiedLeadId) setCopied(false); copyResetTimerRef.current = null; }, 1800); };
  const addLearner = () => { clearCopyTimer(); setCopied(false); setData((value) => nextLearnerData(value)); meta.current = newSubmissionMeta(); setStep(1); setStatus("idle"); setMessage(""); setLeadId(""); setErrors({}); setKeptContact(true); requestAnimationFrame(() => reveal(document.getElementById("form-section-title"))); };
  if (status === "success") return <div id="trial-form-container" className="mx-auto w-full max-w-[780px] rounded-2xl border border-emerald-200 bg-white p-6 text-center shadow-sm sm:p-10" role="status"><Icon name="CheckCircle2" size={30} className="mx-auto text-emerald-800" /><h2 className="mt-4 text-2xl font-bold text-stone-800">Your trial request has been received</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-stone-600">We’ll contact you through WhatsApp or email to arrange Trial 1.</p><div className="mt-4 flex items-center justify-center gap-2 text-xs text-stone-500"><span>Reference: {leadId}</span><button type="button" className="min-h-11 px-2 font-bold text-emerald-800 underline" onClick={copyReference} aria-live="polite">{copied ? "Copied" : "Copy"}</button></div><div className="mx-auto mt-5 max-w-md rounded-xl bg-stone-50 p-4 text-left"><h3 className="text-sm font-bold text-stone-800">What happens next</h3><ol className="mt-2 space-y-1 text-sm leading-6 text-stone-600"><li>1. We review your availability.</li><li>2. We contact you through WhatsApp or email.</li><li>3. We confirm Trial 1 with your teacher.</li></ol></div><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><button type="button" onClick={addLearner} className="min-h-12 rounded-lg bg-emerald-800 px-5 text-sm font-bold text-white">Add another learner</button><Link to="/" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-emerald-700 px-5 text-sm font-bold text-emerald-800">Return to homepage</Link></div></div>;
  const options = <T extends string>(items: readonly { value: T; label: string }[], field: "learnerType" | "ageGroup" | "mainGoal" | "preferredTime") => items.map((o, i) => <label key={o.value} className={choice(data[field] === o.value)}><input id={i === 0 ? field : undefined} type="radio" name={field} checked={data[field] === o.value} onChange={() => { setApiErrorFields(v=>{const n=new Set(v);n.delete(field);return n}); if (field === "learnerType") { setData((value) => withLearnerType(value, o.value as "child" | "self")); setErrors((value) => ({ ...value, learnerType: undefined, ageGroup: undefined })); } else update(field, o.value as FormData[typeof field]); }} aria-invalid={Boolean(visibleErrors[field])} aria-describedby={described(field)} />{o.label}</label>);
  const stepHeadings = STEP_HEADINGS;
  return <div id="trial-form-container" className="mx-auto w-full max-w-[760px] rounded-2xl border border-stone-200 bg-white shadow-sm"><TrialProgress step={step as 1 | 2 | 3} />
    <form onSubmit={submit} noValidate className="p-4 pb-6 sm:p-6"><h2 ref={headingRef} tabIndex={-1} className="text-xl font-bold text-stone-800">{step === 1 ? "About the learner" : step === 2 ? "Contact details" : "Class availability"}</h2>{keptContact && step === 1 && <p className="mt-2 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900">We kept your contact details to save time.</p>}<p className="mt-1 text-sm text-stone-600">{step === 1 ? "Help us understand the right starting point." : step === 2 ? "Tell us how to reach you to arrange the classes." : "Choose general preferences; the final time is confirmed with you."}</p>
      {step === 1 && <div className="mt-6 space-y-6"><fieldset><legend className="text-sm font-bold">Who is learning? *</legend><div className="mt-2 grid grid-cols-2 gap-2">{options(LEARNER_TYPE_OPTIONS, "learnerType")}</div><ErrorText field="learnerType" errors={visibleErrors} /></fieldset><fieldset><legend className="text-sm font-bold">Age group *</legend><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">{options(AGE_GROUP_OPTIONS, "ageGroup")}</div><ErrorText field="ageGroup" errors={visibleErrors} /></fieldset><fieldset><legend className="text-sm font-bold">Main goal *</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{options(MAIN_GOAL_OPTIONS, "mainGoal")}</div><ErrorText field="mainGoal" errors={visibleErrors} /></fieldset></div>}
      {step === 2 && <div className="mt-6 grid gap-4 sm:grid-cols-2">
        <label className="text-sm font-bold">{learnerNameLabel(data.learnerType)}<input id="contactName" value={data.contactName} onChange={(e) => update("contactName", e.target.value)} className={input("contactName")} /><ErrorText field="contactName" errors={visibleErrors} /></label>
        {guardianRequired && <label className="text-sm font-bold">Parent/guardian name *<input id="guardianName" value={data.guardianName} onChange={(e) => update("guardianName", e.target.value)} className={input("guardianName")} aria-invalid={Boolean(visibleErrors.guardianName)} aria-describedby={described("guardianName")} /><ErrorText field="guardianName" errors={visibleErrors} /></label>}
        <SearchCombobox id="countryName" label="Country of residence *" value={data.countryCode} error={errors.countryName} placeholder="Search country, ISO code, or calling code" onChange={chooseCountry} options={countryOptions.map((c) => ({ value: c.code, label: c.name, group: c.group, search: `${c.code} +${getCountryCallingCode(c.code)}`, leading: <CountryFlag country={c.code} countryName={c.name} />, trailing: `+${getCountryCallingCode(c.code)}` }))} />
        <label className="text-sm font-bold">{regionMeta.label}<input id="region" value={data.region} maxLength={100} placeholder={regionMeta.placeholder} onChange={(e) => update("region", e.target.value)} className={input("region")} /><span className="mt-1 block text-xs font-normal text-stone-600">This helps us confirm your local class time.</span><ErrorText field="region" errors={errors} /></label>
        <div className="sm:col-span-2"><SearchCombobox id="timeZone" label="Your time zone *" value={data.timeZone} error={errors.timeZone} placeholder="Search city, friendly label, or IANA value" onChange={(value) => { update("timeZone", value); setRecentZones((current) => { const next = addRecentIdentifier(current, value, zoneValues); writeSessionIdentifiers(RECENT_ZONES_KEY, next, zoneValues); return next; }); }} options={timeZoneOptions} /><span className="mt-1 block text-xs text-stone-600">You can change this at any time.</span></div>
        <label className="text-sm font-bold sm:col-span-2">WhatsApp number *<div className={`mt-1.5 flex min-h-12 w-full items-center rounded-lg border bg-white focus-within:ring-2 focus-within:ring-emerald-700 focus-within:ring-offset-2 ${errors.whatsapp ? "border-red-500" : "border-stone-300"}`}><PhoneCountrySelect country={phoneCountry} options={countries} onChange={changePhoneCountry} /><span aria-hidden="true" className="shrink-0 border-l border-stone-200 px-3 text-sm font-semibold text-stone-700">{phoneCountry ? `+${getCountryCallingCode(phoneCountry)}` : "+"}</span><input id="whatsapp" type="tel" inputMode="tel" autoComplete="tel" value={phoneNational} onChange={(event) => updatePhoneEntry(event.target.value)} placeholder={getNationalPhonePlaceholder(phoneCountry)} aria-describedby={`whatsapp-help${errors.whatsapp ? " whatsapp-error" : ""}`} className="min-w-0 flex-1 self-stretch rounded-r-lg border-0 bg-transparent px-3 text-sm font-normal text-stone-900 outline-none placeholder:text-stone-400" /></div><span id="whatsapp-help" className="mt-1 block text-xs font-normal text-stone-600">Use a number that can receive WhatsApp messages.</span>{data.whatsapp && data.countryCode && parsePhoneNumber(data.whatsapp)?.country && parsePhoneNumber(data.whatsapp)?.country !== data.countryCode && <span className="mt-1 block text-xs font-normal text-stone-600">This WhatsApp number uses a different country code from your country of residence. That is okay—please confirm it is your active number.</span>}<ErrorText field="whatsapp" errors={errors} /></label>
        <label className="text-sm font-bold sm:col-span-2">Email address *<input id="email" type="email" value={data.email} onChange={(e) => update("email", e.target.value)} onBlur={() => update("email", data.email.trim().toLowerCase())} className={input("email")} autoComplete="email" />{suggestion && commonDomains.includes(suggestion) && <button type="button" className="mt-1 text-xs text-emerald-800 underline" onClick={() => update("email", `${data.email.split("@")[0]}@${suggestion}`)}>Did you mean {suggestion}?</button>}<ErrorText field="email" errors={errors} /></label>
      </div>}
      {step === 3 && <div className="mt-6 space-y-6"><fieldset><legend className="text-sm font-bold">Preferred days *</legend><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{PREFERRED_DAY_OPTIONS.map((o, i) => <label key={o.value} className={choice(data.preferredDays.includes(o.value))}><input id={i === 0 ? "preferredDays" : undefined} type="checkbox" checked={data.preferredDays.includes(o.value)} onChange={() => update("preferredDays", data.preferredDays.includes(o.value) ? data.preferredDays.filter((v) => v !== o.value) : [...data.preferredDays, o.value])} />{o.label}</label>)}</div><ErrorText field="preferredDays" errors={visibleErrors} /></fieldset><fieldset><legend className="text-sm font-bold">Preferred general time *</legend><p className="mt-1 text-xs text-stone-600">Times shown in {timeZoneLabel(data.timeZone || detectedZone)}</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{PREFERRED_TIME_OPTIONS.map((o, i) => { const range = { morning: "6:00 AM–12:00 PM", afternoon: "12:00 PM–5:00 PM", evening: "5:00 PM–10:00 PM" }[o.value]; return <label key={o.value} className={`${choice(data.preferredTime === o.value)} flex-col items-start gap-0`}><span className="flex items-center gap-2"><input id={i === 0 ? "preferredTime" : undefined} type="radio" name="preferredTime" checked={data.preferredTime === o.value} onChange={() => update("preferredTime", o.value)} />{o.label}</span><span className="pl-6 text-xs font-normal text-stone-600">{range}</span></label>; })}</div><p className="mt-2 text-xs text-stone-600">We’ll confirm the exact class time with you.</p><p className="mt-1 text-xs text-stone-600">These are general availability ranges, not confirmed appointment times.</p><ErrorText field="preferredTime" errors={visibleErrors} /></fieldset><label className="block text-sm font-bold">Anything else we should know? (optional)<textarea id="notes" value={data.notes} onChange={(e) => update("notes", e.target.value)} maxLength={1000} rows={3} placeholder="Current Quran level, previous learning, preferred language, learning needs, or scheduling notes." className="mt-1.5 w-full rounded-lg border border-stone-300 p-3 text-sm font-normal" /><ErrorText field="notes" errors={visibleErrors} /></label><div><label className="flex min-h-11 cursor-pointer items-start gap-3 text-sm leading-6"><input id="consent" type="checkbox" checked={data.consent} onChange={(e) => update("consent", e.target.checked)} className="mt-1.5 h-5 w-5" />I agree that Tajweed Scholars may contact me about these trial classes through WhatsApp or email.</label><ErrorText field="consent" errors={visibleErrors} /></div></div>}
      <div className="absolute -left-[10000px] h-px w-px overflow-hidden" aria-hidden="true"><input name="website" value={honeypot} onChange={(e) => setHoneypot(e.target.value)} tabIndex={-1} autoComplete="off" /></div>{status !== "idle" && <div role="status" className={`mt-5 rounded-lg border p-3 text-sm ${status === "error" ? "border-red-300 bg-red-50 text-red-800" : "border-stone-200 bg-stone-50"}`}>{status === "submitting" ? "Submitting your request…" : message}</div>}<div className="mt-6 flex gap-3 border-t border-stone-200 pt-5">{step > 1 && <button type="button" onClick={() => showStep(step - 1)} className="min-h-11 rounded-lg border border-emerald-700 px-5 text-sm font-bold text-emerald-800">Back</button>}<button type={step === 3 ? "submit" : "button"} onClick={step === 3 ? undefined : next} disabled={status === "submitting"} className="min-h-12 flex-1 rounded-lg bg-emerald-800 px-4 text-sm font-bold text-white disabled:opacity-60">{step === 3 ? "Request My 3 Free Trial Classes" : "Continue"}</button></div></form></div>;
};
